version: "3.9"
services:
  app:
    build: .
    container_name: travel-mate-server
    ports:
      - "5000:5000"
    env_file: 
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: travel-mate-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: travelmate
    ports:
      - "5432:5432"
